### ISSUE TITLE
Rust icon might not show up

### ISSUE THREAD

**Issue by winnie334** [winnie334/RustCommitTracker#1]
No idea what is causing this, but it seems running the program manually fixes it.

Possibly there's something wrong with the icon path, you can try to change

*"rusticon.ico"* 

with the full path to the .ico file.

**Comment by JayHerlth** [comment]
Does this bug still exist with the current code?

**Comment by winnie334** [comment]
Absolutely no idea, but it's not me who originally had this issue.

We can close this issue and see if anyone reports it again in the future.
